- name: Deploy Artifactory Edge HA Node
  hosts: artifactory
  become: true
  roles:
    - install_edge_ha

- name: Install and configure Nginx
  hosts: nginx
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy sgithub OAuth certificate
      copy:
        src: files/sgithub.crt
        dest: /usr/local/share/ca-certificates/sgithub.crt

    - name: Update CA certificates
      command: update-ca-certificates

    - name: Deploy Nginx config for Artifactory
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
