- name: Add Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ filebeat_version.split('.')[0] }}.x/apt stable main"
    state: present
    update_cache: yes


- name: Download Filebeat tar.gz
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"
    dest: "/tmp/filebeat-{{ filebeat_version }}.tar.gz"

- name: Extract Filebeat archive
  unarchive:
    src: "/tmp/filebeat-{{ filebeat_version }}.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Create symlink for Filebeat
  file:
    src: "/opt/filebeat-{{ filebeat_version }}-linux-x86_64"
    dest: "/opt/filebeat"
    state: link
    force: yes

- name: Copy Filebeat binary to /usr/local/bin
  copy:
    src: "/opt/filebeat/filebeat"
    dest: "/usr/local/bin/filebeat"
    mode: '0755'
    remote_src: yes

- name: Deploy Filebeat configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat

- name: Enable Filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: started

- name: Deploy custom Filebeat systemd unit file
  copy:
    src: filebeat.service
    dest: /etc/systemd/system/filebeat.service
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
